export const memoryFragments = [
  {
    id: 'memory-014',
    code: 'Memory #014',
    location: 'museum-origins',
    title: 'First engineering notebook',
    excerpt: 'The first notes where curiosity turned into intentional practice.',
  },
  {
    id: 'memory-032',
    code: 'Memory #032',
    location: 'museum-origins',
    title: 'School discipline milestone',
    excerpt: 'A period that established consistency before complexity arrived.',
  },
  {
    id: 'memory-067',
    code: 'Memory #067',
    location: 'museum-origins',
    title: 'Entry into engineering',
    excerpt: 'The moment structured problem solving became a long-term path.',
  },
  {
    id: 'memory-091',
    code: 'Memory #091',
    location: 'training-facility',
    title: 'Java foundations checkpoint',
    excerpt: 'Core language mastery shifted learning from random to deliberate.',
  },
  {
    id: 'memory-108',
    code: 'Memory #108',
    location: 'training-facility',
    title: 'Collections and data modeling',
    excerpt: 'Data structure fluency improved both speed and clarity of design.',
  },
  {
    id: 'memory-126',
    code: 'Memory #126',
    location: 'training-facility',
    title: 'Concurrency understanding',
    excerpt: 'Multithreading practice introduced precision under uncertainty.',
  },
  {
    id: 'memory-149',
    code: 'Memory #149',
    location: 'challenge-galaxy',
    title: 'Debugging under time pressure',
    excerpt: 'Failures became actionable once every step was logged as evidence.',
  },
  {
    id: 'memory-172',
    code: 'Memory #172',
    location: 'challenge-galaxy',
    title: 'Contest collaboration signal',
    excerpt: 'Clear communication reduced repair time more than guesswork ever did.',
  },
  {
    id: 'memory-188',
    code: 'Memory #188',
    location: 'challenge-galaxy',
    title: 'Resilience protocol',
    excerpt: 'Post-failure analysis consistently produced stronger next iterations.',
  },
  {
    id: 'memory-203',
    code: 'Memory #203',
    location: 'mission-control',
    title: 'Mission brief architecture',
    excerpt: 'Projects became easier to explain once documented as decision records.',
  },
  {
    id: 'memory-219',
    code: 'Memory #219',
    location: 'mission-control',
    title: 'Outcome traceability',
    excerpt: 'Problem, objective, and solution framing improved implementation focus.',
  },
  {
    id: 'memory-233',
    code: 'Memory #233',
    location: 'mission-control',
    title: 'Evidence-driven retrospectives',
    excerpt: 'Mission summaries became reusable guidance for future systems.',
  },
  {
    id: 'memory-247',
    code: 'Memory #247',
    location: 'research-labs',
    title: 'Experiment protocol refinement',
    excerpt: 'Defining success signals before runs improved interpretation quality.',
  },
  {
    id: 'memory-264',
    code: 'Memory #264',
    location: 'research-labs',
    title: 'Failure category mapping',
    excerpt: 'Systematic failure labels accelerated iteration and reproducibility.',
  },
  {
    id: 'memory-278',
    code: 'Memory #278',
    location: 'research-labs',
    title: 'Research-to-build bridge',
    excerpt: 'Lab outputs became practical implementation patterns across modules.',
  },
  {
    id: 'memory-291',
    code: 'Memory #291',
    location: 'achievement-observatory',
    title: '365-day completion marker',
    excerpt: 'A major milestone proving discipline can be engineered deliberately.',
  },
  {
    id: 'memory-307',
    code: 'Memory #307',
    location: 'achievement-observatory',
    title: 'NEXUS launch record',
    excerpt: 'A full multi-module system shipped with cohesive narrative structure.',
  },
  {
    id: 'memory-322',
    code: 'Memory #322',
    location: 'achievement-observatory',
    title: 'Archive curator deployment',
    excerpt: 'Local knowledge retrieval enabled instant archival navigation.',
  },
  {
    id: 'memory-336',
    code: 'Memory #336',
    location: 'present-station',
    title: 'Current operations cadence',
    excerpt: 'Daily logging keeps active work interpretable while still in motion.',
  },
  {
    id: 'memory-351',
    code: 'Memory #351',
    location: 'present-station',
    title: 'Learning tracker signal',
    excerpt: 'Skill development is managed as a live system, not a side task.',
  },
  {
    id: 'memory-367',
    code: 'Memory #367',
    location: 'present-station',
    title: 'Focus budgeting model',
    excerpt: 'Priority mapping reduced drift and improved decision quality.',
  },
  {
    id: 'memory-384',
    code: 'Memory #384',
    location: 'future-galaxy',
    title: 'Future destination map',
    excerpt: 'Long-horizon goals were encoded as actionable destinations.',
  },
  {
    id: 'memory-401',
    code: 'Memory #401',
    location: 'future-galaxy',
    title: 'Forecast window protocol',
    excerpt: 'Future plans shifted from abstract goals to mission forecasts.',
  },
  {
    id: 'memory-420',
    code: 'Memory #420',
    location: 'future-galaxy',
    title: 'Continuation clause',
    excerpt: 'The story now ends with open vectors rather than fixed endpoints.',
  },
]

export const fragmentLocations = {
  'achievement-observatory': 'Achievement Observatory',
  'challenge-galaxy': 'Challenge Galaxy',
  'future-galaxy': 'Future Galaxy',
  'mission-control': 'Mission Control',
  'museum-origins': 'Museum of Origins',
  'present-station': 'Present Station',
  'research-labs': 'Research Labs',
  'training-facility': 'Training Facility',
}

export const completionMilestones = [25, 50, 75, 100]

export function getFragmentsByLocation(location) {
  return memoryFragments.filter((fragment) => fragment.location === location)
}